In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset['classification'].value_counts()

yes    249
no     150
Name: classification, dtype: int64

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
independent=dataset.drop(['classification_yes'],axis=1)

independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [5]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

param_grid=[{'penalty': ['l1', 'l2', 'elasticnet', None]},
         {'solver': ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']}]

grid=GridSearchCV(LogisticRegression(),param_grid,refit=True,cv=5,n_jobs=-1,verbose=3,scoring='f1_weighted')

#grid.fit(x_train,y_train)

In [9]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    4.0s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    4.3s finished
/Users/Max/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Max/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid=[{'penalty': ['l1', 'l2', 'elasticnet', None]},
                         {'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                     'newton-cholesky', 'sag', 'saga']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [10]:
re=grid.cv_results_
print(re)

{'mean_fit_time': array([0.00246201, 0.02000775, 0.00122566, 0.00109882, 0.01227298,
       0.00643568, 0.02369204, 0.00124435, 0.12132664, 0.06224308]), 'std_fit_time': array([8.52438076e-04, 3.28849485e-03, 1.65756402e-04, 6.44717343e-05,
       3.10455990e-03, 2.61922624e-03, 5.54956184e-03, 1.61932621e-04,
       5.18742668e-02, 6.53596429e-02]), 'mean_score_time': array([0.        , 0.00466108, 0.        , 0.        , 0.00253201,
       0.00242524, 0.00317736, 0.        , 0.00455298, 0.00518999]), 'std_score_time': array([0.00000000e+00, 1.29677038e-03, 0.00000000e+00, 0.00000000e+00,
       8.98734917e-04, 7.96853816e-05, 1.49687967e-03, 0.00000000e+00,
       1.63665676e-03, 4.89560599e-03]), 'param_penalty': masked_array(data=['l1', 'l2', 'elasticnet', None, --, --, --, --, --, --],
             mask=[False, False, False, False,  True,  True,  True,  True,
                    True,  True],
       fill_value='?',
            dtype=object), 'param_solver': masked_array(data=[--, --, --, --, 'lbfgs', 'liblinear', 'newton-cg',
                   'newton-cholesky', 'sag', 'saga'],
             mask=[ True,  True,  True,  True, False, False, False, False,
                   False, False],
       fill_value='?',
            dtype=object), 'params': [{'penalty': 'l1'}, {'penalty': 'l2'}, {'penalty': 'elasticnet'}, {'penalty': None}, {'solver': 'lbfgs'}, {'solver': 'liblinear'}, {'solver': 'newton-cg'}, {'solver': 'newton-cholesky'}, {'solver': 'sag'}, {'solver': 'saga'}], 'split0_test_score': array([       nan, 0.98156912,        nan,        nan, 0.98156912,
       0.96328363, 0.98156912,        nan, 0.98156912, 0.98156912]), 'split1_test_score': array([       nan, 0.98101383,        nan,        nan, 0.98101383,
       0.98123317, 0.98101383,        nan, 0.98123317, 0.98123317]), 'split2_test_score': array([       nan, 0.98121703,        nan,        nan, 0.98121703,
       0.962573  , 0.98121703,        nan, 0.98121703, 0.98121703]), 'split3_test_score': array([       nan, 1.        ,        nan,        nan, 1.        ,
       0.98121703, 1.        ,        nan, 1.        , 0.98121703]), 'split4_test_score': array([       nan, 1.        ,        nan,        nan, 1.        ,
       0.98121703, 1.        ,        nan, 1.        , 0.98121703]), 'mean_test_score': array([       nan, 0.98876   ,        nan,        nan, 0.98876   ,
       0.97390477, 0.98876   ,        nan, 0.98880386, 0.98129068]), 'std_test_score': array([       nan, 0.00917914,        nan,        nan, 0.00917914,
       0.00896506, 0.00917914,        nan, 0.00914247, 0.00013936]), 'rank_test_score': array([ 7,  2,  8,  9,  2,  6,  2, 10,  1,  5], dtype=int32)}

In [11]:
y_pred=grid.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[51  0]
 [ 1 81]]

In [13]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)

In [14]:
print(cr)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,average='weighted')
print('The f1_macro value for best param:{}'.format(grid.best_params_), f1_macro)

The f1_macro value for best param:{'solver': 'sag'} 0.9924946382275899

In [16]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [17]:
table=pd.DataFrame.from_dict(re)
print(table)

   mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       0.002462      0.000852         0.000000        0.000000            l1
1       0.020008      0.003288         0.004661        0.001297            l2
2       0.001226      0.000166         0.000000        0.000000    elasticnet
3       0.001099      0.000064         0.000000        0.000000          None
4       0.012273      0.003105         0.002532        0.000899           NaN
5       0.006436      0.002619         0.002425        0.000080           NaN
6       0.023692      0.005550         0.003177        0.001497           NaN
7       0.001244      0.000162         0.000000        0.000000           NaN
8       0.121327      0.051874         0.004553        0.001637           NaN
9       0.062243      0.065360         0.005190        0.004896           NaN

      param_solver                         params  split0_test_score  \
0              NaN              {'penalty': 'l1'}                NaN
1              NaN              {'penalty': 'l2'}           0.981569
2              NaN      {'penalty': 'elasticnet'}                NaN
3              NaN              {'penalty': None}                NaN
4            lbfgs            {'solver': 'lbfgs'}           0.981569
5        liblinear        {'solver': 'liblinear'}           0.963284
6        newton-cg        {'solver': 'newton-cg'}           0.981569
7  newton-cholesky  {'solver': 'newton-cholesky'}                NaN
8              sag              {'solver': 'sag'}           0.981569
9             saga             {'solver': 'saga'}           0.981569

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                NaN                NaN                NaN                NaN
1           0.981014           0.981217           1.000000           1.000000
2                NaN                NaN                NaN                NaN
3                NaN                NaN                NaN                NaN
4           0.981014           0.981217           1.000000           1.000000
5           0.981233           0.962573           0.981217           0.981217
6           0.981014           0.981217           1.000000           1.000000
7                NaN                NaN                NaN                NaN
8           0.981233           0.981217           1.000000           1.000000
9           0.981233           0.981217           0.981217           0.981217

   mean_test_score  std_test_score  rank_test_score
0              NaN             NaN                7
1         0.988760        0.009179                2
2              NaN             NaN                8
3              NaN             NaN                9
4         0.988760        0.009179                2
5         0.973905        0.008965                6
6         0.988760        0.009179                2
7              NaN             NaN               10
8         0.988804        0.009142                1
9         0.981291        0.000139                5

In [18]:
import pickle 
pickle.dump(grid,open('LogRegGrid.pkl','wb'))