In [1]:
import pandas as pd

In [15]:
dataset=pd.read_csv("CKD.csv")
dataset['classification'].value_counts()

yes    249
no     150
Name: classification, dtype: int64

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [11]:
independent=dataset.drop(['classification_yes'],axis=1)

independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [10]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [22]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

param_grid=[{'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
           {'gamma':['scale', 'auto']},{'C': [1, 10, 100]}]

grid=GridSearchCV(SVC(probability=True),param_grid,refit=True,cv=5,n_jobs=-1,verbose=3,scoring='f1_weighted')

#grid.fit(x_train,y_train)

In [23]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-1)]: Done  38 out of  45 | elapsed:    3.9s remaining:    0.7s
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:    3.9s finished
/Users/Max/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid=[{'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
                         {'gamma': ['scale', 'auto']}, {'C': [1, 10, 100]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [24]:
re=grid.cv_results_
print(re)

{'mean_fit_time': array([0.01902266, 0.02254214, 0.01100941, 0.01193628, 0.00999818,
       0.01250591, 0.01362519, 0.0079895 , 0.00786633]), 'std_fit_time': array([0.00657168, 0.00701726, 0.00344632, 0.00232033, 0.0020758 ,
       0.00421265, 0.00714551, 0.00134516, 0.00280301]), 'mean_score_time': array([0.00553722, 0.00304565, 0.00301948, 0.00673618, 0.0057817 ,
       0.00305762, 0.003337  , 0.00338631, 0.00335135]), 'std_score_time': array([0.00214371, 0.00037915, 0.0007537 , 0.00375776, 0.00397583,
       0.00046559, 0.00101614, 0.00098308, 0.00155961]), 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', --, --, --, --, --],
             mask=[False, False, False, False,  True,  True,  True,  True,
                    True],
       fill_value='?',
            dtype=object), 'param_gamma': masked_array(data=[--, --, --, --, 'scale', 'auto', --, --, --],
             mask=[ True,  True,  True,  True, False, False,  True,  True,
                    True],
       fill_value='?',
            dtype=object), 'param_C': masked_array(data=[--, --, --, --, --, --, 1, 10, 100],
             mask=[ True,  True,  True,  True,  True,  True, False, False,
                   False],
       fill_value='?',
            dtype=object), 'params': [{'kernel': 'linear'}, {'kernel': 'poly'}, {'kernel': 'rbf'}, {'kernel': 'sigmoid'}, {'gamma': 'scale'}, {'gamma': 'auto'}, {'C': 1}, {'C': 10}, {'C': 100}], 'split0_test_score': array([0.98156912, 1.        , 0.98156912, 1.        , 0.98156912,
       0.98156912, 0.98156912, 0.96328363, 0.96328363]), 'split1_test_score': array([0.96226415, 0.96175502, 0.98101383, 0.96226415, 0.98101383,
       0.98101383, 0.98101383, 0.98101383, 0.98101383]), 'split2_test_score': array([0.98121703, 0.98121703, 0.98121703, 0.962573  , 0.98121703,
       0.98121703, 0.98121703, 1.        , 1.        ]), 'split3_test_score': array([1.        , 0.96182604, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.98103098]), 'split4_test_score': array([1.        , 0.98103098, 1.        , 0.98121703, 1.        ,
       1.        , 1.        , 1.        , 1.        ]), 'mean_test_score': array([0.98501006, 0.97716582, 0.98876   , 0.98121084, 0.98876   ,
       0.98876   , 0.98876   , 0.98885949, 0.98506569]), 'std_test_score': array([0.01409255, 0.01432168, 0.00917914, 0.01680721, 0.00917914,
       0.00917914, 0.00917914, 0.01475135, 0.0138074 ]), 'rank_test_score': array([7, 9, 2, 8, 2, 2, 2, 1, 6], dtype=int32)}

In [25]:
y_pred=grid.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[51  0]
 [ 3 79]]

In [28]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)

In [29]:
print(cr)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [34]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,average='weighted')
print('The f1_macro value for best param:{}'.format(grid.best_params_), f1_macro)

The f1_macro value for best param:{'C': 10} 0.9775556904684072

In [35]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9992826398852224

In [36]:
table=pd.DataFrame.from_dict(re)
print(table)

   mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.019023      0.006572         0.005537        0.002144       linear
1       0.022542      0.007017         0.003046        0.000379         poly
2       0.011009      0.003446         0.003019        0.000754          rbf
3       0.011936      0.002320         0.006736        0.003758      sigmoid
4       0.009998      0.002076         0.005782        0.003976          NaN
5       0.012506      0.004213         0.003058        0.000466          NaN
6       0.013625      0.007146         0.003337        0.001016          NaN
7       0.007990      0.001345         0.003386        0.000983          NaN
8       0.007866      0.002803         0.003351        0.001560          NaN

  param_gamma param_C                 params  split0_test_score  \
0         NaN     NaN   {'kernel': 'linear'}           0.981569
1         NaN     NaN     {'kernel': 'poly'}           1.000000
2         NaN     NaN      {'kernel': 'rbf'}           0.981569
3         NaN     NaN  {'kernel': 'sigmoid'}           1.000000
4       scale     NaN     {'gamma': 'scale'}           0.981569
5        auto     NaN      {'gamma': 'auto'}           0.981569
6         NaN       1               {'C': 1}           0.981569
7         NaN      10              {'C': 10}           0.963284
8         NaN     100             {'C': 100}           0.963284

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.962264           0.981217           1.000000           1.000000
1           0.961755           0.981217           0.961826           0.981031
2           0.981014           0.981217           1.000000           1.000000
3           0.962264           0.962573           1.000000           0.981217
4           0.981014           0.981217           1.000000           1.000000
5           0.981014           0.981217           1.000000           1.000000
6           0.981014           0.981217           1.000000           1.000000
7           0.981014           1.000000           1.000000           1.000000
8           0.981014           1.000000           0.981031           1.000000

   mean_test_score  std_test_score  rank_test_score
0         0.985010        0.014093                7
1         0.977166        0.014322                9
2         0.988760        0.009179                2
3         0.981211        0.016807                8
4         0.988760        0.009179                2
5         0.988760        0.009179                2
6         0.988760        0.009179                2
7         0.988859        0.014751                1
8         0.985066        0.013807                6

In [37]:
import pickle 
pickle.dump(grid,open('SVCGrid.pkl','wb'))