In [22]:
import pandas as pd

In [23]:
dataset=pd.read_csv("CKD.csv")
dataset['classification'].value_counts()

yes    249
no     150
Name: classification, dtype: int64

In [24]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [25]:
independent=dataset.drop(['classification_yes'],axis=1)

independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [26]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

param_grid=[{'max_features': ['sqrt', 'log2', None]},
           {'criterion':['gini', 'entropy','log_loss']},
           {'splitter':['best','random']}]

grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,cv=5,n_jobs=-1,verbose=3,scoring='f1_weighted')

#grid.fit(x_train,y_train)

In [30]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    4.7s
[Parallel(n_jobs=-1)]: Done  40 out of  40 | elapsed:    4.7s finished

GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=-1,
             param_grid=[{'max_features': ['sqrt', 'log2', None]},
                         {'criterion': ['gini', 'entropy', 'log_loss']},
                         {'splitter': ['best', 'random']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [31]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
print(table)

   mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.006454      0.001607         0.005960        0.002964
1       0.004639      0.002565         0.002302        0.000136
2       0.005230      0.001794         0.003264        0.002116
3       0.004466      0.000482         0.003428        0.001383
4       0.004329      0.000638         0.002477        0.000066
5       0.003255      0.000659         0.000000        0.000000
6       0.003957      0.000684         0.002638        0.000647
7       0.003288      0.000329         0.002208        0.000128

  param_max_features param_criterion param_splitter  \
0               sqrt             NaN            NaN
1               log2             NaN            NaN
2               None             NaN            NaN
3                NaN            gini            NaN
4                NaN         entropy            NaN
5                NaN        log_loss            NaN
6                NaN             NaN           best
7                NaN             NaN         random

                      params  split0_test_score  split1_test_score  \
0   {'max_features': 'sqrt'}           0.926567           0.981014
1   {'max_features': 'log2'}           0.963284           0.924528
2     {'max_features': None}           0.962963           0.981014
3      {'criterion': 'gini'}           0.981378           0.923510
4   {'criterion': 'entropy'}           0.872428           0.922185
5  {'criterion': 'log_loss'}                NaN                NaN
6       {'splitter': 'best'}           0.944707           0.981014
7     {'splitter': 'random'}           0.963284           0.943041

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           0.907035           0.962264           0.923652         0.940106
1           0.981217           0.961826           0.923652         0.950901
2           0.907035           0.922492           0.981031         0.950907
3           0.962573           0.943093           0.962264         0.954564
4           0.962573           0.922492           0.981031         0.932142
5                NaN                NaN                NaN              NaN
6           0.907035           0.943093           0.981031         0.951376
7           0.981217           0.962264           0.981217         0.966205

   std_test_score  rank_test_score
0        0.027248                6
1        0.022934                5
2        0.030631                4
3        0.019689                2
4        0.037614                7
5             NaN                8
6        0.027702                3
7        0.014222                1

In [32]:
y_pred=grid.predict(x_test)

In [33]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[51  0]
 [ 5 77]]

In [34]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)

In [35]:
print(cr)

              precision    recall  f1-score   support

           0       0.91      1.00      0.95        51
           1       1.00      0.94      0.97        82

    accuracy                           0.96       133
   macro avg       0.96      0.97      0.96       133
weighted avg       0.97      0.96      0.96       133

In [36]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,average='weighted')
print('The f1_macro value for best param:{}'.format(grid.best_params_), f1_macro)

The f1_macro value for best param:{'splitter': 'random'} 0.9626932787797391

In [37]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9695121951219512

In [38]:
import pickle 
pickle.dump(grid,open('DTGrid.pkl','wb'))